"""Add index for reports

Revision ID: 62714e94b4a4
Revises: da99c246f924
Create Date: 2026-04-01 05:53:57.018986
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62714e94b4a4'
down_revision: Union[str, None] = 'da99c246f924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reservation_reports', 'reservations', ['hotel_id', 'status', 'check_in', 'check_out'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reservation_reports', table_name='reservations')
    # ### end Alembic commands ###
