"""Add instagram_page_id to Hotel

Revision ID: 12dbdfdcfd52
Revises: b28e0866ce82
Create Date: 2026-04-02 10:15:17.726975
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12dbdfdcfd52'
down_revision: Union[str, None] = 'b28e0866ce82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('instagram_page_id', sa.String(length=100), nullable=True, comment='Instagram Page ID linked to this hotel for DM bookings'))
    op.create_index(op.f('ix_hotels_instagram_page_id'), 'hotels', ['instagram_page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotels_instagram_page_id'), table_name='hotels')
    op.drop_column('hotels', 'instagram_page_id')
    # ### end Alembic commands ###
