"""Drop unique constraints from WhatsApp numbers

Revision ID: a2ca69503c7a
Revises: 62714e94b4a4
Create Date: 2026-04-01 06:36:51.555847
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ca69503c7a'
down_revision: Union[str, None] = '62714e94b4a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hotels_whatsapp_phone_number_id_key', 'hotels', type_='unique')
    op.drop_index('ix_hotels_whatsapp_number', table_name='hotels')
    op.create_index(op.f('ix_hotels_whatsapp_number'), 'hotels', ['whatsapp_number'], unique=False)
    op.create_index(op.f('ix_hotels_whatsapp_phone_number_id'), 'hotels', ['whatsapp_phone_number_id'], unique=False)
    op.drop_index('ix_reservation_reports', table_name='reservations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reservation_reports', 'reservations', ['hotel_id', 'status', 'check_in', 'check_out'], unique=False)
    op.drop_index(op.f('ix_hotels_whatsapp_phone_number_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_whatsapp_number'), table_name='hotels')
    op.create_index('ix_hotels_whatsapp_number', 'hotels', ['whatsapp_number'], unique=True)
    op.create_unique_constraint('hotels_whatsapp_phone_number_id_key', 'hotels', ['whatsapp_phone_number_id'])
    # ### end Alembic commands ###
