"""Add owner_email to hotel

Revision ID: b1bb3f6c10eb
Revises: b0d507cdd216
Create Date: 2026-04-04 08:38:44.720025
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1bb3f6c10eb'
down_revision: Union[str, None] = 'b0d507cdd216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('owner_email', sa.String(length=255), nullable=True, comment='Owner email address for receiving reports'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'owner_email')
    # ### end Alembic commands ###
