"""Add daily pricing model

Revision ID: e551d4e78d67
Revises: 675889cecfd9
Create Date: 2026-04-02 08:20:28.410581
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e551d4e78d67'
down_revision: Union[str, None] = '675889cecfd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('competitor_hotel_name', sa.String(length=255), nullable=False, comment='Name of the competitor hotel'),
    sa.Column('date', sa.Date(), nullable=False, comment='Date of the pricing'),
    sa.Column('my_price', sa.Numeric(precision=10, scale=2), nullable=False, comment="My hotel's price"),
    sa.Column('competitor_price', sa.Numeric(precision=10, scale=2), nullable=False, comment="Competitor's price"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'competitor_hotel_name', 'date', name='uq_hotel_competitor_date')
    )
    op.create_index(op.f('ix_daily_pricing_hotel_id'), 'daily_pricing', ['hotel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_pricing_hotel_id'), table_name='daily_pricing')
    op.drop_table('daily_pricing')
    # ### end Alembic commands ###
