"""Add guest info and reviews

Revision ID: 675889cecfd9
Revises: a2ca69503c7a
Create Date: 2026-04-02 06:53:54.827361
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675889cecfd9'
down_revision: Union[str, None] = 'a2ca69503c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=True, comment='Optional link to the specific reservation being reviewed'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Rating 1-5 stars'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Guest review text'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_guest_id'), 'reviews', ['guest_id'], unique=False)
    op.create_index(op.f('ix_reviews_hotel_id'), 'reviews', ['hotel_id'], unique=False)
    op.add_column('guests', sa.Column('nationality', sa.String(length=100), nullable=True, comment='Guest nationality, e.g. سعودي، مصري'))
    op.add_column('guests', sa.Column('id_type', sa.String(length=50), nullable=True, comment='Document type: هوية، جواز، إقامة'))
    op.add_column('guests', sa.Column('id_number', sa.String(length=50), nullable=True, comment='ID/passport/iqama number'))
    op.add_column('guests', sa.Column('notes', sa.Text(), nullable=True, comment='Special notes about this guest'))
    op.add_column('guests', sa.Column('total_stays', sa.Integer(), nullable=False, server_default='0', comment='Number of completed stays'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'total_stays')
    op.drop_column('guests', 'notes')
    op.drop_column('guests', 'id_number')
    op.drop_column('guests', 'id_type')
    op.drop_column('guests', 'nationality')
    op.drop_index(op.f('ix_reviews_hotel_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_guest_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
