"""Add category to Review

Revision ID: 3edc4498b615
Revises: bcc6f1205406
Create Date: 2026-04-02 09:51:26.467572
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edc4498b615'
down_revision: Union[str, None] = 'bcc6f1205406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('category', sa.String(length=50), server_default='general', nullable=False, comment='Category: cleanliness, service, maintenance, general'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'category')
    # ### end Alembic commands ###
