"""add_per_hotel_tokens

Revision ID: 287aba07a4c0
Revises: a7f3c2d9e123
Create Date: 2026-04-02 23:35:12.308531
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287aba07a4c0'
down_revision: Union[str, None] = 'a7f3c2d9e123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('whatsapp_api_token', sa.String(length=500), nullable=True, comment='Per-hotel WhatsApp Business API token'))
    op.add_column('hotels', sa.Column('telegram_bot_token', sa.String(length=255), nullable=True, comment='Per-hotel Telegram Bot API token'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'telegram_bot_token')
    op.drop_column('hotels', 'whatsapp_api_token')
    # ### end Alembic commands ###
