"""Add ai_reply_suggestion to Review

Revision ID: b28e0866ce82
Revises: 3edc4498b615
Create Date: 2026-04-02 10:04:47.507537
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28e0866ce82'
down_revision: Union[str, None] = '3edc4498b615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('ai_reply_suggestion', sa.Text(), nullable=True, comment='AI generated suggested reply to the guest'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'ai_reply_suggestion')
    # ### end Alembic commands ###
