"""Add AuditLog and ProcessedMessage

Revision ID: da99c246f924
Revises: e33a34f828ba
Create Date: 2026-04-01 03:10:17.314413
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da99c246f924'
down_revision: Union[str, None] = 'e33a34f828ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_messages',
    sa.Column('id', sa.String(length=255), nullable=False, comment='WhatsApp message ID (wamid...)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_messages_created_at'), 'processed_messages', ['created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('actor_phone', sa.String(length=50), nullable=False, comment='The WhatsApp number of the user performing the action'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='e.g., APPROVE_RESERVATION, REJECT_RESERVATION'),
    sa.Column('target_id', sa.String(length=255), nullable=True, comment='The ID of the impacted resource (reservation_id, etc.)'),
    sa.Column('details', sa.Text(), nullable=True, comment='Extra JSON or text details about the action'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_phone'), 'audit_logs', ['actor_phone'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_hotel_id'), 'audit_logs', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_hotel_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_phone'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_processed_messages_created_at'), table_name='processed_messages')
    op.drop_table('processed_messages')
    # ### end Alembic commands ###
