"""add_room_type_to_daily_pricing

Revision ID: 696691a49055
Revises: b1bb3f6c10eb
Create Date: 2026-04-04 09:47:13.065228
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696691a49055'
down_revision: Union[str, None] = 'b1bb3f6c10eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_pricing', sa.Column('room_type_id', sa.UUID(), nullable=True))
    op.drop_constraint('uq_hotel_competitor_date', 'daily_pricing', type_='unique')
    op.create_index(op.f('ix_daily_pricing_room_type_id'), 'daily_pricing', ['room_type_id'], unique=False)
    op.create_unique_constraint('uq_hotel_competitor_room_date', 'daily_pricing', ['hotel_id', 'competitor_hotel_name', 'room_type_id', 'date'])
    op.create_foreign_key(None, 'daily_pricing', 'room_types', ['room_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_pricing', type_='foreignkey')
    op.drop_constraint('uq_hotel_competitor_room_date', 'daily_pricing', type_='unique')
    op.drop_index(op.f('ix_daily_pricing_room_type_id'), table_name='daily_pricing')
    op.create_unique_constraint('uq_hotel_competitor_date', 'daily_pricing', ['hotel_id', 'competitor_hotel_name', 'date'])
    op.drop_column('daily_pricing', 'room_type_id')
    # ### end Alembic commands ###
